alter table materials add description varchar(200);

update materials set description = 'Vindskeder på rejsning' where id = 1;
update materials set description = 'Sternbrædder til siderne Carport del' where id = 2;
update materials set description = 'Sternbrædder til siderne Skur del (deles)' where id = 3;
update materials set description = 'Byg-selv spær (skal samles) 8 stk.' where id = 4;
update materials set description = 'Stolper nedraves 90 cm. i jord + skråstiver' where id = 5;
update materials set description = 'Remme i sider, sadles ned i stolper Carport del' where id = 6;
update materials set description = 'Remme i sider, sadles ned i stolper Skur del' where id = 7;
update materials set description = 'Løsholter i siderne af skur' where id = 8;
update materials set description = 'Løsholter i gavle af skur' where id = 9;
update materials set description = 'Vand bræt på vindskeder' where id = 10;
update materials set description = 'Beklædning af gavle 1 på 2' where id = 11;
update materials set description = 'Beklædning af skur 1 på 2' where id = 12;
update materials set description = 'Til montering oven på tagfodslægte' where id = 13;
update materials set description = 'Til z på bagside af dør' where id = 14;
update materials set description = 'Til montering på spær, 7 rækker lægter på hver skiftevis 1 hel & 1 halv lægte' where id = 15;
update materials set description = 'Toplægte til montering af rygsten lægges i toplægte holder' where id = 16;
update materials set description = 'Monteres på taglægter 6 rækker af 24 sten på hver side på taget' where id = 17;
update materials set description = 'Monteres på toplægte med medfølgende beslag se tagstens vejledning' where id = 18;
update materials set description = 'Monteres på toppen af spæret (til toplægte)' where id = 19;
update materials set description = 'Til montering af rygsten' where id = 20;
update materials set description = 'Til montering af tagsten, alle ydersten + hver anden fastgøres' where id = 21;
update materials set description = 'Til montering af spær på rem' where id = 22;
update materials set description = 'Til montering af spær på rem' where id = 23;
update materials set description = 'Til dør i skur' where id = 24;
update materials set description = 'Til dør i skur' where id = 25;
update materials set description = 'Til montering af løsholter' where id = 26;
update materials set description = 'Til montering af Stern, vindskeder, vindkrys & vandbræt' where id = 27;
update materials set description = 'Til montering af universalbeslag + toplæget' where id = 28;
update materials set description = 'Til taglægter' where id = 29;
update materials set description = 'Til montering af rem på stolper' where id = 30;
update materials set description = 'Til montering af rem på stolper' where id = 31;
update materials set description = 'Til montering af yderste bræt ved beklædning' where id = 32;
update materials set description = 'Til montering af inderste bræt ved beklædning' where id = 33;

update materials set description = 'Understernbrædder til for & bagende' where id = 34;
update materials set description = 'Understernbrædder til siderne' where id = 35;
update materials set description = 'Oversternbrædder til for og bagende' where id = 36;
update materials set description = 'Oversternbrædder til siderne' where id = 37;
update materials set description = 'Til z på bagside af dør' where id = 38;
update materials set description = 'Løsholter til skur gavle' where id = 39;
update materials set description = 'Løsholter til skur sider' where id = 40;
update materials set description = 'Remme i sider, sadles ned i stolper' where id = 41;
update materials set description = 'Remme i sider, sadles ned i stolper (Skur del, deles)' where id = 42;
update materials set description = 'Spær, monteres på rem' where id = 43;
update materials set description = 'Stolper nedgraves 90cm. i jord' where id = 44;
update materials set description = 'Til beklædning af skur 1 på 2' where id = 45;
update materials set description = 'Vandbrædt på stern i sider' where id = 46;
update materials set description = 'Vandbrædt på stern i for & bagende' where id = 47;
update materials set description = 'Tagplader monteres på spær' where id = 48;
update materials set description = 'Tagplader monteres på spær' where id = 49;
update materials set description = 'Til vindkryds på spær' where id = 50;
update materials set description = 'Til montering af spær på rem' where id = 51;
update materials set description = 'Til montering af spær på rem' where id = 52;
update materials set description = 'Til lås på skur' where id = 53;
update materials set description = 'Til skurdør' where id = 54;
update materials set description = 'Til montering af løsholter i skur' where id = 55;
update materials set description = 'Skruer til tagplader' where id = 56;
update materials set description = 'Til montering af sterng & vandbrædt' where id = 57;
update materials set description = 'Til montering af universalbeslag + hulbånd' where id = 58;
update materials set description = 'Til montering af rem på stolper' where id = 59;
update materials set description = 'Til montering af rem på stolper' where id = 60;
update materials set description = 'Til montering af yderste beklædning' where id = 61;
update materials set description = 'Til montering af inderste beklædning' where id = 62;

UPDATE properties SET value = 11 WHERE name = 'version';