SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE customers
    CHANGE COLUMN name firstname VARCHAR(255) NOT NULL,
    ADD COLUMN lastname VARCHAR(255) NOT NULL;

ALTER TABLE orders
    ADD COLUMN timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

SET FOREIGN_KEY_CHECKS = 1;

UPDATE properties SET value = 5 WHERE name = 'version';
